spring:
  datasource:
    url: jdbc:mysql://localhost:3308/alkemypractice?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false